version: '3.8'

x-configs:
  policy: &policy
    restart: always
  logging: &logging
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

services:
  db:
    image: postgres:13.1-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./scripts/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    ports:
      - "5432:5432"
    <<: [*logging, *policy]

  app:
    build:
      context: ./
      target: dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: ./scripts/start.sh
    environment:
      - DATABASE_URL=${DATABASE_URL}
    <<: [*logging, *policy]

volumes:
  db-data:
