version: '3.8'

# Configuración de políticas y registro
x-configs:
  policy: &policy
    restart: always
  logging: &logging
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

services:
  db:
    image: postgres:13.1-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - .db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    <<: [*logging, *policy]

  app:
    build:
      context: ./
      target: dev
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    command: yarn run dev
    <<: [*logging, *policy]
